### ISSUE TITLE
Unable to find path

### ISSUE THREAD

**Issue by floggle** [p1c2u/openapi-spec-validator#50]
No matter what path I use, I always get this error:

`<urlopen error [WinError 3] The system cannot find the path specified: ''>`

The path can be either absolute to a file, or to the http://localhost/openapi.json

As you can see in the error, despite calling it with:
`openapi-spec-validator http://localhost/openjson.api`
the error is implying that I'm not providing any path at all.

for the filepath, I've tried both forward and back slashes:
`c:\my_path\openapi.json`
and
`c:/my_path/openapi.sjon`

Python 3.6, installed via pip

**Comment by kearnh** [comment]
The problem seems to be in __main__.py where it is simply adding "file://" to the filename to create a URI. This won't work in windows because three slashes are required, i.e. "file:///". The URI should rather be constructed using "pathlib.Path(filename).as_uri()" which should work across platforms, or for Python 2 urllib.request.pathname2url and then add "file" schema in front.

**Comment by p1c2u** [comment]
Fixed with #51. Closing.
